//Gun Macros
#macro REVOLVER 0
#macro SUBMACHINEGUN 1
#macro MACHINEGUN 2
#macro ASSAULTRIFFLE 3
#macro TRIPPLEMACHINEGUN 4
#macro BOW 5
#macro AUTOBOW 6
#macro DOUBLEBOW 7
#macro MULTIBOW 8
#macro METALBOW 9
#macro ROCKETLAUNCHER 10
#macro LARGEROCKETLAUNCHER 11
#macro GRENADELAUNCHER 12
#macro AUTOGRENADELAUNCHER 13
#macro ROCKETBOW 14
#macro HANDGRENADE 15
#macro BOMB 16

#macro GUNSPRITE 0
#macro RELOADTIME 1
#macro RECOILSTART 2
#macro SHOTAMOUNT 3
#macro SHOTSPREAD 4
#macro SHOTSPEED 5
#macro SHOTBUFFER 6
#macro ATTACKPOINTS 7
#macro XORGIN 8
#macro YORGIN 9
#macro BULLETOBJ 10
#macro BULLETSPT 11
#macro BULLETSND 12
#macro BULLETSHAKE 13
#macro BULLETAMOUNT 14
#macro BULLETANGLE 15
#macro BULLETINDEX 16
#macro RELOADINDEX 17

hp = 5;
hp_max = 5;

dead = false;
done = false;

// Movement vars
hit_dir = 0;
hit_spd = 0;
hit_amt = 0;
hit_now = false;
x_speed_ = 0;
y_speed_ = 0;
x_portal = 0;
y_portal = 0;
max_speed_ = 2;
acceleration_ = .5;
recovery_remain = 0;
flash = 0;
water = 0;
footprints = 0;
kick = false;
kick_multiplier = 1.2;
kick_hold = 25;
kick_current = 0;

// Controller vars
controller = 0;
hascontrol = true;
gunangle = 0;
firing = false;
currentshot = -1;
currentreload = 0;
currentrecoil = 0;
currentbuffer = 0;
weapon_xoffset = 0;

// Gun vars
currentGun = noone;
gunsprite = 0;
reloadtime = 0;
recoilstart = 0;
shotamount = 0;
shotspread = 0;
shotspeed = 0;
shotbuffer = 0;
xorgin = 0;
yorgin = 0;
bulletobj = noone;
bulletspt = noone;
bulletsnd = noone;
bulletshake = [];
bulletamount = 0;
bulletangle = 0;
bulletindex = 0;
reloadindex = 0;

#region Bullet Weapons
guns[REVOLVER, GUNSPRITE] = sptRevolver;
guns[REVOLVER, RELOADTIME] = 10;
guns[REVOLVER, RECOILSTART] = 0;
guns[REVOLVER, SHOTAMOUNT] = 1;
guns[REVOLVER, SHOTSPREAD] = 0;
guns[REVOLVER, SHOTSPEED] = 10;
guns[REVOLVER, SHOTBUFFER] = 30;
guns[REVOLVER, ATTACKPOINTS] = 1;
guns[REVOLVER, XORGIN] = -10;
guns[REVOLVER, YORGIN] = 11;
guns[REVOLVER, BULLETOBJ] = objBullet;
guns[REVOLVER, BULLETSPT] = sptBullet;
guns[REVOLVER, BULLETSND] = sndRevolver;
guns[REVOLVER, BULLETSHAKE] = [2,7,0.2,0.2,10];
guns[REVOLVER, BULLETAMOUNT] = 1;
guns[REVOLVER, BULLETANGLE] = [0];
guns[REVOLVER, BULLETINDEX] = 0;
guns[REVOLVER, BULLETINDEX] = 0;
guns[REVOLVER, RELOADINDEX] = 1;

guns[SUBMACHINEGUN, GUNSPRITE] = sptSubMachine;
guns[SUBMACHINEGUN, RELOADTIME] = 30;
guns[SUBMACHINEGUN, RECOILSTART] = 0;
guns[SUBMACHINEGUN, SHOTAMOUNT] = 3;
guns[SUBMACHINEGUN, SHOTSPREAD] = 3;
guns[SUBMACHINEGUN, SHOTSPEED] = 10;
guns[SUBMACHINEGUN, SHOTBUFFER] = 3;
guns[SUBMACHINEGUN, ATTACKPOINTS] = 1;
guns[SUBMACHINEGUN, XORGIN] = -13;
guns[SUBMACHINEGUN, YORGIN] = 11;
guns[SUBMACHINEGUN, BULLETOBJ] = objBullet;
guns[SUBMACHINEGUN, BULLETSPT] = sptBullet;
guns[SUBMACHINEGUN, BULLETSND] = sndRevolver;
guns[SUBMACHINEGUN, BULLETSHAKE] = [2,7,0.2,0.2,10];
guns[SUBMACHINEGUN, BULLETAMOUNT] = 1;
guns[SUBMACHINEGUN, BULLETANGLE] = [0];
guns[SUBMACHINEGUN, BULLETINDEX] = 0;
guns[SUBMACHINEGUN, RELOADINDEX] = 1;

guns[MACHINEGUN, GUNSPRITE] = sptMachineGun;
guns[MACHINEGUN, RELOADTIME] = 1;
guns[MACHINEGUN, RECOILSTART] = 0;
guns[MACHINEGUN, SHOTAMOUNT] = -1;
guns[MACHINEGUN, SHOTSPREAD] = 4;
guns[MACHINEGUN, SHOTSPEED] = 10;
guns[MACHINEGUN, SHOTBUFFER] = 5;
guns[MACHINEGUN, ATTACKPOINTS] = 1;
guns[MACHINEGUN, XORGIN] = -20;
guns[MACHINEGUN, YORGIN] = 11;
guns[MACHINEGUN, BULLETOBJ] = objBullet;
guns[MACHINEGUN, BULLETSPT] = sptBullet;
guns[MACHINEGUN, BULLETSND] = sndRevolver;
guns[MACHINEGUN, BULLETSHAKE] = [2,7,0.2,0.2,10];
guns[MACHINEGUN, BULLETAMOUNT] = 1;
guns[MACHINEGUN, BULLETANGLE] = [0];
guns[MACHINEGUN, BULLETINDEX] = 0;
guns[MACHINEGUN, RELOADINDEX] = 1;

guns[ASSAULTRIFFLE, GUNSPRITE] = sptAssault;
guns[ASSAULTRIFFLE, RELOADTIME] = 1;
guns[ASSAULTRIFFLE, RECOILSTART] = 0;
guns[ASSAULTRIFFLE, SHOTAMOUNT] = -1;
guns[ASSAULTRIFFLE, SHOTSPREAD] = 2;
guns[ASSAULTRIFFLE, SHOTSPEED] = 10;
guns[ASSAULTRIFFLE, SHOTBUFFER] = 9;
guns[ASSAULTRIFFLE, ATTACKPOINTS] = 3;
guns[ASSAULTRIFFLE, XORGIN] = -20;
guns[ASSAULTRIFFLE, YORGIN] = 11;
guns[ASSAULTRIFFLE, BULLETOBJ] = objBullet;
guns[ASSAULTRIFFLE, BULLETSPT] = sptBullet;
guns[ASSAULTRIFFLE, BULLETSND] = sndRevolver;
guns[ASSAULTRIFFLE, BULLETSHAKE] = [2,7,0.2,0.2,10];
guns[ASSAULTRIFFLE, BULLETAMOUNT] = 1;
guns[ASSAULTRIFFLE, BULLETANGLE] =[0];
guns[ASSAULTRIFFLE, BULLETINDEX] = 0;
guns[ASSAULTRIFFLE, RELOADINDEX] = 1;

guns[TRIPPLEMACHINEGUN, GUNSPRITE] = sptTripleMachine;
guns[TRIPPLEMACHINEGUN, RELOADTIME] = 1;
guns[TRIPPLEMACHINEGUN, RECOILSTART] = 0;
guns[TRIPPLEMACHINEGUN, SHOTAMOUNT] = -1;
guns[TRIPPLEMACHINEGUN, SHOTSPREAD] = 1;
guns[TRIPPLEMACHINEGUN, SHOTSPEED] = 10;
guns[TRIPPLEMACHINEGUN, SHOTBUFFER] = 5;
guns[TRIPPLEMACHINEGUN, ATTACKPOINTS] = 1;
guns[TRIPPLEMACHINEGUN, XORGIN] = -20;
guns[TRIPPLEMACHINEGUN, YORGIN] = 11;
guns[TRIPPLEMACHINEGUN, BULLETOBJ] = objBullet;
guns[TRIPPLEMACHINEGUN, BULLETSPT] = sptBullet;
guns[TRIPPLEMACHINEGUN, BULLETSND] = sndRevolver;
guns[TRIPPLEMACHINEGUN, BULLETSHAKE] = [2,7,0.2,0.2,10];
guns[TRIPPLEMACHINEGUN, BULLETAMOUNT] = 3;
guns[TRIPPLEMACHINEGUN, BULLETANGLE] = [-8,0,8];
guns[TRIPPLEMACHINEGUN, BULLETINDEX] = 0;
guns[TRIPPLEMACHINEGUN, RELOADINDEX] = 1;
#endregion Bullet Weapons

#region Bolt Weapons
guns[BOW, GUNSPRITE] = sptBow;
guns[BOW, RELOADTIME] = 30;
guns[BOW, RECOILSTART] = 0;
guns[BOW, SHOTAMOUNT] = 1;
guns[BOW, SHOTSPREAD] = 0;
guns[BOW, SHOTSPEED] = 10;
guns[BOW, SHOTBUFFER] = 30;
guns[BOW, ATTACKPOINTS] = 3;
guns[BOW, XORGIN] = -10;
guns[BOW, YORGIN] = 3;
guns[BOW, BULLETOBJ] = objArrow;
guns[BOW, BULLETSPT] = sptArrow;
guns[BOW, BULLETSND] = sndRevolver;
guns[BOW, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[BOW, BULLETAMOUNT] = 1;
guns[BOW, BULLETANGLE] = [0];
guns[BOW, BULLETINDEX] = 0;
guns[BOW, RELOADINDEX] = 1;

guns[AUTOBOW, GUNSPRITE] = sptAutoBow;
guns[AUTOBOW, RELOADTIME] = 1;
guns[AUTOBOW, RECOILSTART] = 0;
guns[AUTOBOW, SHOTAMOUNT] = -1;
guns[AUTOBOW, SHOTSPREAD] = 4;
guns[AUTOBOW, SHOTSPEED] = 10;
guns[AUTOBOW, SHOTBUFFER] = 10;
guns[AUTOBOW, ATTACKPOINTS] = 3;
guns[AUTOBOW, XORGIN] = -10;
guns[AUTOBOW, YORGIN] = 3;
guns[AUTOBOW, BULLETOBJ] = objArrow;
guns[AUTOBOW, BULLETSPT] = sptArrow;
guns[AUTOBOW, BULLETSND] = sndRevolver;
guns[AUTOBOW, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[AUTOBOW, BULLETAMOUNT] = 1;
guns[AUTOBOW, BULLETANGLE] = [0];
guns[AUTOBOW, BULLETINDEX] = 0;
guns[AUTOBOW, RELOADINDEX] = 1;

guns[DOUBLEBOW, GUNSPRITE] = sptDoubleBow;
guns[DOUBLEBOW, RELOADTIME] = 30;
guns[DOUBLEBOW, RECOILSTART] = 0;
guns[DOUBLEBOW, SHOTAMOUNT] = 1;
guns[DOUBLEBOW, SHOTSPREAD] = 1;
guns[DOUBLEBOW, SHOTSPEED] = 10;
guns[DOUBLEBOW, SHOTBUFFER] = 30;
guns[DOUBLEBOW, ATTACKPOINTS] = 3;
guns[DOUBLEBOW, XORGIN] = -10;
guns[DOUBLEBOW, YORGIN] = 3;
guns[DOUBLEBOW, BULLETOBJ] = objArrow;
guns[DOUBLEBOW, BULLETSPT] = objArrow;
guns[DOUBLEBOW, BULLETSND] = sndRevolver;
guns[DOUBLEBOW, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[DOUBLEBOW, BULLETAMOUNT] = 2;
guns[DOUBLEBOW, BULLETANGLE] = [-4,4];
guns[DOUBLEBOW, BULLETINDEX] = 0;
guns[DOUBLEBOW, RELOADINDEX] = 1;

guns[MULTIBOW, GUNSPRITE] = sptMultiBow;
guns[MULTIBOW, RELOADTIME] = 30;
guns[MULTIBOW, RECOILSTART] = 0;
guns[MULTIBOW, SHOTAMOUNT] = 1;
guns[MULTIBOW, SHOTSPREAD] = 1;
guns[MULTIBOW, SHOTSPEED] = 10;
guns[MULTIBOW, SHOTBUFFER] = 30;
guns[MULTIBOW, ATTACKPOINTS] = 3;
guns[MULTIBOW, XORGIN] = -10;
guns[MULTIBOW, YORGIN] = 3;
guns[MULTIBOW, BULLETOBJ] = objArrow;
guns[MULTIBOW, BULLETSPT] = objArrow;
guns[MULTIBOW, BULLETSND] = sndRevolver;
guns[MULTIBOW, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[MULTIBOW, BULLETAMOUNT] = 6;
guns[MULTIBOW, BULLETANGLE] = [-8,-4,0,4,8,12];
guns[MULTIBOW, BULLETINDEX] = 0;
guns[MULTIBOW, RELOADINDEX] = 1;

guns[METALBOW, GUNSPRITE] = sptMetalBow;
guns[METALBOW, RELOADTIME] = 30;
guns[METALBOW, RECOILSTART] = 0;
guns[METALBOW, SHOTAMOUNT] = 1;
guns[METALBOW, SHOTSPREAD] = 0;
guns[METALBOW, SHOTSPEED] = 10;
guns[METALBOW, SHOTBUFFER] = 30;
guns[METALBOW, ATTACKPOINTS] = 5;
guns[METALBOW, XORGIN] = -10;
guns[METALBOW, YORGIN] = 3;
guns[METALBOW, BULLETOBJ] = objArrow;
guns[METALBOW, BULLETSPT] = sptArrow;
guns[METALBOW, BULLETSND] = sndRevolver;
guns[METALBOW, BULLETSHAKE] = [2,7,0.2,0.2,10];
guns[METALBOW, BULLETAMOUNT] = 1;
guns[METALBOW, BULLETANGLE] = [0];
guns[METALBOW, BULLETINDEX] = 1;
guns[METALBOW, RELOADINDEX] = 1;
#endregion Bolt Weapons

#region Bomb Weapons
guns[ROCKETLAUNCHER, GUNSPRITE] = sptRocketLauncher;
guns[ROCKETLAUNCHER, RELOADTIME] = 60;
guns[ROCKETLAUNCHER, RECOILSTART] = 0;
guns[ROCKETLAUNCHER, SHOTAMOUNT] = 1;
guns[ROCKETLAUNCHER, SHOTSPREAD] = 0;
guns[ROCKETLAUNCHER, SHOTSPEED] = 5;
guns[ROCKETLAUNCHER, SHOTBUFFER] = 60;
guns[ROCKETLAUNCHER, ATTACKPOINTS] = 2;
guns[ROCKETLAUNCHER, XORGIN] = -10;
guns[ROCKETLAUNCHER, YORGIN] = 3;
guns[ROCKETLAUNCHER, BULLETOBJ] = objRockets;
guns[ROCKETLAUNCHER, BULLETSPT] = sptRockets;
guns[ROCKETLAUNCHER, BULLETSND] = sndRevolver;
guns[ROCKETLAUNCHER, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[ROCKETLAUNCHER, BULLETAMOUNT] = 1;
guns[ROCKETLAUNCHER, BULLETANGLE] = [0];
guns[ROCKETLAUNCHER, BULLETINDEX] = 1;
guns[ROCKETLAUNCHER, RELOADINDEX] = 2;

guns[LARGEROCKETLAUNCHER, GUNSPRITE] = sptLargeRocketLauncher;
guns[LARGEROCKETLAUNCHER, RELOADTIME] = 60;
guns[LARGEROCKETLAUNCHER, RECOILSTART] = 0;
guns[LARGEROCKETLAUNCHER, SHOTAMOUNT] = 1;
guns[LARGEROCKETLAUNCHER, SHOTSPREAD] = 0;
guns[LARGEROCKETLAUNCHER, SHOTSPEED] = 5;
guns[LARGEROCKETLAUNCHER, SHOTBUFFER] = 60;
guns[LARGEROCKETLAUNCHER, ATTACKPOINTS] = 1;
guns[LARGEROCKETLAUNCHER, XORGIN] = -10;
guns[LARGEROCKETLAUNCHER, YORGIN] = 5;
guns[LARGEROCKETLAUNCHER, BULLETOBJ] = objRockets;
guns[LARGEROCKETLAUNCHER, BULLETSPT] = sptRockets;
guns[LARGEROCKETLAUNCHER, BULLETSND] = sndRevolver;
guns[LARGEROCKETLAUNCHER, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[LARGEROCKETLAUNCHER, BULLETAMOUNT] = 1;
guns[LARGEROCKETLAUNCHER, BULLETANGLE] = [0];
guns[LARGEROCKETLAUNCHER, BULLETINDEX] = 2;
guns[LARGEROCKETLAUNCHER, RELOADINDEX] = 2;

guns[GRENADELAUNCHER, GUNSPRITE] = sptGrenadeLauncher;
guns[GRENADELAUNCHER, RELOADTIME] = 60;
guns[GRENADELAUNCHER, RECOILSTART] = 0;
guns[GRENADELAUNCHER, SHOTAMOUNT] = 1;
guns[GRENADELAUNCHER, SHOTSPREAD] = 0;
guns[GRENADELAUNCHER, SHOTSPEED] = 4;
guns[GRENADELAUNCHER, SHOTBUFFER] = 60;
guns[GRENADELAUNCHER, ATTACKPOINTS] = 0;
guns[GRENADELAUNCHER, XORGIN] = -10;
guns[GRENADELAUNCHER, YORGIN] = 5;
guns[GRENADELAUNCHER, BULLETOBJ] = objLaunchedGrenade;
guns[GRENADELAUNCHER, BULLETSPT] = sptLaunchedGrenade;
guns[GRENADELAUNCHER, BULLETSND] = sndRevolver;
guns[GRENADELAUNCHER, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[GRENADELAUNCHER, BULLETAMOUNT] = 1;
guns[GRENADELAUNCHER, BULLETANGLE] = [0];
guns[GRENADELAUNCHER, BULLETINDEX] = 3;
guns[GRENADELAUNCHER, RELOADINDEX] = 1;

guns[AUTOGRENADELAUNCHER, GUNSPRITE] = sptAutoGrenadeLauncher;
guns[AUTOGRENADELAUNCHER, RELOADTIME] = 1;
guns[AUTOGRENADELAUNCHER, RECOILSTART] = 0;
guns[AUTOGRENADELAUNCHER, SHOTAMOUNT] = -1;
guns[AUTOGRENADELAUNCHER, SHOTSPREAD] = 0;
guns[AUTOGRENADELAUNCHER, SHOTSPEED] = 4;
guns[AUTOGRENADELAUNCHER, SHOTBUFFER] = 25;
guns[AUTOGRENADELAUNCHER, ATTACKPOINTS] = 0;
guns[AUTOGRENADELAUNCHER, XORGIN] = -10;
guns[AUTOGRENADELAUNCHER, YORGIN] = 5;
guns[AUTOGRENADELAUNCHER, BULLETOBJ] = objLaunchedGrenade;
guns[AUTOGRENADELAUNCHER, BULLETSPT] = sptLaunchedGrenade;
guns[AUTOGRENADELAUNCHER, BULLETSND] = sndRevolver;
guns[AUTOGRENADELAUNCHER, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[AUTOGRENADELAUNCHER, BULLETAMOUNT] = 1;
guns[AUTOGRENADELAUNCHER, BULLETANGLE] = [0];
guns[AUTOGRENADELAUNCHER, BULLETINDEX] = 3;
guns[AUTOGRENADELAUNCHER, RELOADINDEX] = 1;

guns[ROCKETBOW, GUNSPRITE] = sptRocketBow;
guns[ROCKETBOW, RELOADTIME] = 30;
guns[ROCKETBOW, RECOILSTART] = 0;
guns[ROCKETBOW, SHOTAMOUNT] = 1;
guns[ROCKETBOW, SHOTSPREAD] = 0;
guns[ROCKETBOW, SHOTSPEED] = 10;
guns[ROCKETBOW, SHOTBUFFER] = 30;
guns[ROCKETBOW, ATTACKPOINTS] = 3;
guns[ROCKETBOW, XORGIN] = -10;
guns[ROCKETBOW, YORGIN] = 3;
guns[ROCKETBOW, BULLETOBJ] = objRockets;
guns[ROCKETBOW, BULLETSPT] = sptRockets;
guns[ROCKETBOW, BULLETSND] = sndRevolver;
guns[ROCKETBOW, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[ROCKETBOW, BULLETAMOUNT] = 1;
guns[ROCKETBOW, BULLETANGLE] = [0];
guns[ROCKETBOW, BULLETINDEX] = 0;
guns[ROCKETBOW, RELOADINDEX] = 1;

guns[HANDGRENADE, GUNSPRITE] = sptHandGrenade;
guns[HANDGRENADE, RELOADTIME] = 60;
guns[HANDGRENADE, RECOILSTART] = 0;
guns[HANDGRENADE, SHOTAMOUNT] = 1;
guns[HANDGRENADE, SHOTSPREAD] = 0;
guns[HANDGRENADE, SHOTSPEED] = 4;
guns[HANDGRENADE, SHOTBUFFER] = 60;
guns[HANDGRENADE, ATTACKPOINTS] = 0;
guns[HANDGRENADE, XORGIN] = -10;
guns[HANDGRENADE, YORGIN] = 5;
guns[HANDGRENADE, BULLETOBJ] = objHandGrenade;
guns[HANDGRENADE, BULLETSPT] = sptHandGrenade;
guns[HANDGRENADE, BULLETSND] = sndRevolver;
guns[HANDGRENADE, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[HANDGRENADE, BULLETAMOUNT] = 1;
guns[HANDGRENADE, BULLETANGLE] = [0];
guns[HANDGRENADE, BULLETINDEX] = 3;
guns[HANDGRENADE, RELOADINDEX] = 2;

guns[BOMB, GUNSPRITE] = sptBomb;
guns[BOMB, RELOADTIME] = 60;
guns[BOMB, RECOILSTART] = 0;
guns[BOMB, SHOTAMOUNT] = 1;
guns[BOMB, SHOTSPREAD] = 0;
guns[BOMB, SHOTSPEED] = 4;
guns[BOMB, SHOTBUFFER] = 60;
guns[BOMB, ATTACKPOINTS] = 0;
guns[BOMB, XORGIN] = -10;
guns[BOMB, YORGIN] = 5;
guns[BOMB, BULLETOBJ] = objBomb;
guns[BOMB, BULLETSPT] = sptBomb;
guns[BOMB, BULLETSND] = sndRevolver;
guns[BOMB, BULLETSHAKE] = [1,6,0.2,0.2,7];
guns[BOMB, BULLETAMOUNT] = 1;
guns[BOMB, BULLETANGLE] = [0];
guns[BOMB, BULLETINDEX] = 2;
guns[BOMB, RELOADINDEX] = 10;
#endregion Bomb Weapons

#region Energy Weapons
#endregion Energy Weapons

instance_create_layer(x, y, "Todd", objCamera);

set_weapon(LARGEROCKETLAUNCHER);